# Generated by superflore -- DO NOT EDIT
#
# Copyright Test

inherit ros_distro_testdistro
inherit ros_superflore_generated

DESCRIPTION = "Test fixture for simple_pkg"
AUTHOR = "Test Maintainer <test@example.com>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://package.xml;beginline=7;endline=7;md5=82f0323c08605e5b6f343b05213cf7cc"

ROS_CN = "simple_pkg"
ROS_BPN = "simple_pkg"

ROS_BUILD_DEPENDS = "\
    libfoo \
"

ROS_BUILDTOOL_DEPENDS = "\
    cmake-native \
"

ROS_EXPORT_DEPENDS = ""

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = ""

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = "\
    libbar \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/example/simple-pkg-release/archive/release/testdistro/simple_pkg/1.0.0-1.tar.gz
ROS_BRANCH ?= "branch=release/testdistro/simple_pkg"
SRC_URI = "git://github.com/example/simple-pkg-release;${ROS_BRANCH};protocol=https"
SRCREV = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
