BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"
BBFILE_COLLECTIONS += "meta-repro"
BBFILE_PATTERN_meta-repro = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-repro = "10"
LAYERSERIES_COMPAT_meta-repro = "wrynose"
